# Moderne CLI GAV
cli.groupId=io.moderne
cli.artifactId=moderne-cli
cli.version=RELEASE
# Repository configuration
repository.id=central
repository.type=default
repository.url=https://repo1.maven.org/maven2/
# Repository authentication configuration (Optional)
# repository.username=username
# repository.password=password
# Repository proxy configuration (Optional)
# proxy.type=https
# proxy.host=localhost
# proxy.port=-1
# Repository proxy user configuration (Optional)
# proxy.username=username
# proxy.password=password
wrapper.groupId=com.github.modw
wrapper.artifactId=modw
wrapper.version=0.0.1-SNAPSHOT
wrapper.qualifier=pg

