name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v-*' # Push events to matching v-*, i.e. v-1.0, v-20.15.10
# https://github.com/softprops/action-gh-release
# https://github.com/ncipollo/release-action
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release to Github
        uses: ncipollo/release-action@v1
      with:
        artifacts: "target/modw-*-distribution*.zip"