on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Release
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        id: setup_jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Evaluation revision
        id: evaluate
        uses: ./.github/actions/revision
      - name: Build with Maven
        run: ./mvnw -B package -Drevision=${{ steps.evaluate.outputs.version }} --file pom.xml
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
#      - name: Upload release distribution asset
#        id: upload_release_asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          VERSION: ${{ steps.get_version.outputs.VERSION }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./target/modw-${{ steps.get_version.outputs.version }}-distribution.zip
#          asset_name: modw-${{ steps.get_version.outputs.version }}-distribution.zip
#          asset_content_type: application/zip